name: chefmax-platform
region: nyc3

services:
  # Backend API Service
  - name: api
    source_dir: back
    github:
      repo: systemadminlightinnoivationsla/chefmax-latam
      branch: main
    dockerfile_path: Dockerfile
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PORT
        value: "3001"
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_REFRESH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_BUCKET_NAME
        value: chefmax-media
        scope: RUN_TIME
      - key: SPACES_ENDPOINT
        value: nyc3.digitaloceanspaces.com
        scope: RUN_TIME
      - key: FRONTEND_URL
        value: ${web.URL}
        scope: RUN_TIME
      - key: CORS_ORIGINS
        value: ${web.URL}
        scope: RUN_TIME
    
    # HTTP configuration
    http_port: 3001
    routes:
      - path: /api
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
      success_threshold: 1
    
    # Resource configuration
    instance_count: 1
    instance_size_slug: basic-xxs

  # Frontend Web Service
  - name: web
    image:
      registry_type: DOCR
      repository: chefmax-backend
      tag: frontend-hybrid
    
    # Environment variables for build
    envs:
      - key: VITE_API_URL
        value: ${api.URL}/api/v1
        scope: BUILD_TIME
      - key: VITE_BACKEND_URL
        value: ${api.URL}
        scope: BUILD_TIME
      - key: VITE_APP_NAME
        value: ChefMax LATAM
        scope: BUILD_TIME
      - key: VITE_APP_VERSION
        value: "1.0.0"
        scope: BUILD_TIME
      - key: VITE_ENVIRONMENT
        value: production
        scope: BUILD_TIME
    
    # HTTP configuration
    http_port: 80
    routes:
      - path: /
    
    # Resource configuration
    instance_count: 1
    instance_size_slug: basic-xxs

# Database (if you need to create one)
databases:
  - name: chefmax-db
    engine: PG
    size: db-s-1vcpu-1gb
    num_nodes: 1
    version: "17"